Repository mikepenz/multiplatform-markdown-renderer, pull requests merged in 2024-10, with the labels that each got.

#213 Making use of EntityConverter to unescape text of leaf nodes
  app/src/screenshotTest/kotlin/com.mikepenz.markdown.ui/SnapshotTests.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownImage.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt
Labels: feature

#219 Fix TextStyle not applied to code in annotated strings
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/MarkdownTypography.kt
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/MarkdownTypography.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownTypography.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt
Labels: fix

#220 Upgrade to Compose-MP 1.7.0-rc01
  gradle/libs.versions.toml
Labels: dependencies, feature
