Repository mikepenz/multiplatform-markdown-renderer, pull requests merged in 2025-01, with the labels that each got.

#264 Fix spacings for nested lists | Simplify logic
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/ListCodeBlockTest_3c07bfff_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/ListCodeBlockTest_db9b1159_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/ListTest_9c1ad4f7_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/ListTest_f33ffe9d_0.png
  app/src/screenshotTest/kotlin/com.mikepenz.markdown.ui/SnapshotTests.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
Labels: fix

#265 Fix publishing
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/PublishingConventionPlugin.kt
Labels: fix

#266 Modify build to use published version catalog and convention plugin
  app-desktop/build.gradle.kts
  app-desktop/gradle.properties
  app-wasm/build.gradle.kts
  app-wasm/gradle.properties
  app/build.gradle.kts
  app/gradle.properties
  build.gradle.kts
  gradle.properties
  gradle/build-logic/convention/build.gradle.kts
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/Android.kt
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/AndroidApplicationConventionPlugin.kt
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/AndroidLibraryConventionPlugin.kt
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/AndroidTestConventionPlugin.kt
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/ComposeConventionPlugin.kt
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/KotlinMultiplatformConventionPlugin.kt
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/PublishingConventionPlugin.kt
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/RootConventionPlugin.kt
  gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/utils/VersionCatalog.kt
  gradle/build-logic/gradle.properties
  gradle/build-logic/settings.gradle.kts
  gradle/libs.versions.toml
  multiplatform-markdown-renderer-code/build.gradle.kts
  multiplatform-markdown-renderer-coil2/build.gradle.kts
  multiplatform-markdown-renderer-coil2/gradle.properties
  multiplatform-markdown-renderer-coil3/build.gradle.kts
  multiplatform-markdown-renderer-m2/build.gradle.kts
  multiplatform-markdown-renderer-m3/build.gradle.kts
  multiplatform-markdown-renderer/build.gradle.kts
  settings.gradle.kts
Labels: other

#267 Upgrade build setup
  app-desktop/build.gradle.kts
  app/build.gradle.kts
  app/gradle.properties
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: other

#268 Improve release signing logic
  .github/workflows/ci.yml
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: other

#273 Update Code Highlights To Automatically Account For Dark Mode
  multiplatform-markdown-renderer-code/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHighlightedCode.kt
Labels: feature

#275 Fix table cell width
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/TableTest_3fc03e55_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/TableTest_5d136f40_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/TableTest_9c1ad4f7_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/TableTest_f33ffe9d_0.png
  app/src/screenshotTest/kotlin/com.mikepenz.markdown.ui/SnapshotTests.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
Labels: fix

#281 Add more configuration options for list paddings
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/DefaultTest_40de0fad_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/DefaultTest_6d087b28_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/ListCodeBlockTest_3c07bfff_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/ListCodeBlockTest_db9b1159_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/ListTest_9c1ad4f7_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/ListTest_f33ffe9d_0.png
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownPadding.kt
Labels: fix

#282 Update dependencies
  .github/workflows/ci.yml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: dependencies
