Repository mikepenz/multiplatform-markdown-renderer, pull requests merged in 2025-03, with the labels that each got.

#331 Improve code fence handling to support varying code fence structures.
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
Labels: fix

#334 Dependency updates
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  settings.gradle.kts
Labels: dependencies

#338 Change EOL handling from `\n` to a single space
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt
Labels: fix

#339 Add option to make EOL be a new line (for direct APIs)
  app-desktop/src/jvmMain/kotlin/main.kt
  app-wasm/src/wasmJsMain/kotlin/Main.kt
  app/src/main/kotlin/com/mikepenz/markdown/MainActivity.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/SnapshotTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/SnapshotTests.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatorSettings.kt
Labels: feature

#346 Move parsing into producer | Introduce loading / error state
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/BlockquotesTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/ElementsInListsTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/SnapshotTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/BlockquotesTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/ElementsInListsTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/SnapshotTests.kt
  multiplatform-markdown-renderer-m2/api/android/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/jvm/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/multiplatform-markdown-renderer-m2.klib.api
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
  multiplatform-markdown-renderer-m3/api/android/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/jvm/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/multiplatform-markdown-renderer-m3.klib.api
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownResult.kt
Labels: feature

#347 Introduce support for reference links
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/m2/LinkTests/LinkTest_dark_3df45f99_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/m2/LinkTests/LinkTest_light_fa4b1f98_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/m3/LinkTests/LinkTest_dark_3df45f99_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/m3/LinkTests/LinkTest_light_fa4b1f98_0.png
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/LinkTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/LinkTests.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatorSettings.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/ReferenceLinkHandler.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt
Labels: feature

#348 Provide `MarkdownState` object with observable state
  app-desktop/src/jvmMain/kotlin/main.kt
  app/src/main/kotlin/com/mikepenz/markdown/ui/Theme.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/BlockquotesTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/ElementsInListsTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/LinkTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/SnapshotTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/util/Helper.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/BlockquotesTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/ElementsInListsTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/LinkTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/SnapshotTests.kt
  app/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/util/Helper.kt
  multiplatform-markdown-renderer-m2/api/android/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/jvm/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/multiplatform-markdown-renderer-m2.klib.api
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
  multiplatform-markdown-renderer-m3/api/android/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/jvm/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/multiplatform-markdown-renderer-m3.klib.api
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownResult.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownState.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt
Labels: feature

#350 Setting to adjust annotator behavior
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatorSettings.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownParagraph.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownAnnotator.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownAnnotatorConfig.kt
Labels: feature

#342 Pass MarkdownList depth via `MarkdownComponentModel`'s `extra` field
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/build.gradle.kts
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
  settings.gradle.kts
Labels: feature

#328 Refactor to support `LazyColumn` as parent container for the markdown content
  multiplatform-markdown-renderer-code/api/android/multiplatform-markdown-renderer-code.api
  multiplatform-markdown-renderer-code/api/jvm/multiplatform-markdown-renderer-code.api
  multiplatform-markdown-renderer-code/api/multiplatform-markdown-renderer-code.klib.api
  multiplatform-markdown-renderer-m2/api/android/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/jvm/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/multiplatform-markdown-renderer-m2.klib.api
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
  multiplatform-markdown-renderer-m3/api/android/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/jvm/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/multiplatform-markdown-renderer-m3.klib.api
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/LazyMarkdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/MarkdownExtension.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
Labels: feature

#351 Cleanup README
  README.md
Labels: other

#352 Introduce MIGRATION guide
  MIGRATION.md
Labels: other

#354 Provide extension function to get `listDepth` from `MarkdownComponentModel`
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
Labels: feature

#355 Cleanup unused arguments
  multiplatform-markdown-renderer-m2/api/android/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/jvm/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/multiplatform-markdown-renderer-m2.klib.api
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
  multiplatform-markdown-renderer-m3/api/android/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/jvm/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/multiplatform-markdown-renderer-m3.klib.api
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
Labels: other

#357 Fix release sample app build
  .github/workflows/ci.yml
Labels: other

#358 Cleanup code
  CONTRIBUTORS.md
  README.md
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/ExtendedSpans.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/RoundedCornerSpanPainter.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/SquigglyUnderlineSpanPainter.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownAnimations.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownColors.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt
  sample/shared/src/commonMain/kotlin/com/mikepenz/markdown/sample/LicensesPage.kt
Labels: other

#360 Add viewport meta tag to `index.html`
  sample/web/src/commonMain/resources/index.html
  sample/web/src/commonMain/resources/styles.css
  sample/web/src/commonMain/resources/unsupported_browser.js
Labels: other

#361 Remove nested handling of elements in `Markdown` and `LazyMarkdown`
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/LazyMarkdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
Labels: other

#362 Improve sample app padding
  sample/shared/src/commonMain/kotlin/com/mikepenz/markdown/sample/MarkDownPage.kt
Labels: other

#363 Offer API to provide `Modifier` for list item content
  MIGRATION.md
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
Labels: feature

#364 Refine stability
  multiplatform-markdown-renderer/build.gradle.kts
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownState.kt
  multiplatform-markdown-renderer/stability_config.conf
Labels: feature
