Repository mikepenz/multiplatform-markdown-renderer, pull requests merged in 2025-04, with the labels that each got.

#366 Update AboutLibraries
  sample/android/build.gradle.kts
  sample/desktop/build.gradle.kts
  sample/desktop/src/jvmMain/kotlin/com/mikepenz/markdown/main.kt
  sample/shared/build.gradle.kts
  sample/shared/src/commonMain/kotlin/com/mikepenz/markdown/sample/LicensesPage.kt
  sample/web/build.gradle.kts
  settings.gradle.kts
Labels: other

#365 Optimize code structure and readability
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
Labels: other

#369 Update AboutLibraries plugin
  sample/desktop/src/commonMain/composeResources/files/aboutlibraries.json
  sample/shared/src/commonMain/composeResources/files/aboutlibraries.json
  sample/web/src/commonMain/composeResources/files/aboutlibraries.json
  settings.gradle.kts
Labels: other

#370 Fix sample deprecation warning from AboutLibs
  sample/web/src/commonMain/kotlin/com/mikepenz/markdown/Main.kt
  settings.gradle.kts
Labels: other

#371 Publish using cross compilation
  .github/workflows/ci.yml
  gradle.properties
Labels: other

#373 Open up `MarkdownElement` Composable
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/LazyMarkdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/MarkdownExtension.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownBlockQuote.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
Labels: feature

#377 Introduce API to parse markdown in VM
  MIGRATION.md
  README.md
  multiplatform-markdown-renderer-m2/api/android/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/jvm/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/multiplatform-markdown-renderer-m2.klib.api
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
  multiplatform-markdown-renderer-m3/api/android/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/jvm/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/multiplatform-markdown-renderer-m3.klib.api
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownState.kt
  sample/shared/src/commonMain/kotlin/com/mikepenz/markdown/sample/MarkDownPage.kt
Labels: feature

#384 Compose 1.8.0 / Compose Multiplatform 1.8.0-rc01
  multiplatform-markdown-renderer-coil3/build.gradle.kts
  sample/desktop/src/commonMain/composeResources/files/aboutlibraries.json
  sample/shared/src/commonMain/composeResources/files/aboutlibraries.json
  sample/web/src/commonMain/composeResources/files/aboutlibraries.json
  settings.gradle.kts
Labels: feature

#386 Make markdown parsing `immediate` if `LocalInspectionMode` is true
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownState.kt
  sample/android/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/util/Helper.kt
  sample/android/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/util/Helper.kt
Labels: fix

#387 Update to AboutLibraries 12.1.0-rc02
  sample/desktop/build.gradle.kts
  sample/desktop/src/commonMain/composeResources/files/aboutlibraries.json
  sample/shared/src/commonMain/composeResources/files/aboutlibraries.json
  sample/web/build.gradle.kts
  sample/web/src/commonMain/composeResources/files/aboutlibraries.json
  settings.gradle.kts
Labels: other

#388 Add export configuration for library definitions
  sample/README.md
  sample/android/build.gradle.kts
  sample/desktop/build.gradle.kts
  sample/shared/build.gradle.kts
  sample/web/build.gradle.kts
Labels: other

#389 AboutLibraries `12.1.0-rc03`
  sample/desktop/src/commonMain/composeResources/files/aboutlibraries.json
  sample/shared/src/commonMain/composeResources/files/aboutlibraries.json
  sample/web/src/commonMain/composeResources/files/aboutlibraries.json
  settings.gradle.kts
Labels: other

#392 Reorder `markdownAnnotator` function arguments
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownAnnotator.kt
Labels: other
