Repository mikepenz/multiplatform-markdown-renderer, pull requests merged in 2025-02, with the labels that each got.

#288 Hover icon on linked text
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
Labels: feature

#290 Expose table row and header to offer more configuration flexibility on tables
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
Labels: feature

#291 Update sample app icon
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_storyblok.xml
  app/src/main/res/values/ic_launcher_background.xml
Labels: other

#292 Fix inline link might navigate wrong
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/TableTest_3fc03e55_0.png
  app/src/debug/screenshotTest/reference/com/mikepenz/markdown/ui/SnapshotTests/TableTest_5d136f40_0.png
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownParagraph.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt
Labels: fix

#293 Include convention plugin from version-catalog
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: other

#295 Fix import not failing in local build
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/SquigglyUnderlineSpanPainter.kt
Labels: fix

#305 Adjust how HARD_LINE_BREAK is interpreted
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt
Labels: fix

#306 Enhance backwards compatiblity
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownImageState.kt
Labels: other

#307 Better handle BR and EOL occurrences
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt
Labels: fix

#308 Update to Coil 3.1.0
  gradle/libs.versions.toml
Labels: dependencies

#313 Fix AUTOLINK in LINK causing issues
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownDivider.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt
Labels: fix

#314 Include Binary Compatibility Validator
  .github/workflows/ci.yml
  build.gradle.kts
  gradle.properties
  multiplatform-markdown-renderer-code/api/android/multiplatform-markdown-renderer-code.api
  multiplatform-markdown-renderer-code/api/jvm/multiplatform-markdown-renderer-code.api
  multiplatform-markdown-renderer-code/api/multiplatform-markdown-renderer-code.klib.api
  multiplatform-markdown-renderer-coil2/api/android/multiplatform-markdown-renderer-coil2.api
  multiplatform-markdown-renderer-coil2/api/jvm/multiplatform-markdown-renderer-coil2.api
  multiplatform-markdown-renderer-coil2/api/multiplatform-markdown-renderer-coil2.klib.api
  multiplatform-markdown-renderer-coil3/api/android/multiplatform-markdown-renderer-coil3.api
  multiplatform-markdown-renderer-coil3/api/jvm/multiplatform-markdown-renderer-coil3.api
  multiplatform-markdown-renderer-coil3/api/multiplatform-markdown-renderer-coil3.klib.api
  multiplatform-markdown-renderer-m2/api/android/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/jvm/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/multiplatform-markdown-renderer-m2.klib.api
  multiplatform-markdown-renderer-m3/api/android/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/jvm/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/multiplatform-markdown-renderer-m3.klib.api
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  settings.gradle.kts
Labels: other

#320 Update dependencies
  gradle/libs.versions.toml
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  settings.gradle.kts
Labels: feature

#317 Introduce support for task list items
  app-desktop/src/jvmMain/kotlin/main.kt
  app/src/main/kotlin/com/mikepenz/markdown/MainActivity.kt
  multiplatform-markdown-renderer-m2/api/android/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/jvm/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/multiplatform-markdown-renderer-m2.klib.api
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/elements/MarkdownCheckBox.kt
  multiplatform-markdown-renderer-m3/api/android/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/jvm/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/multiplatform-markdown-renderer-m3.klib.api
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/elements/MarkdownCheckBox.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCheckBox.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
Labels: feature

#323 `remember` the state created by `derivedStateOf`
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatorSettings.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownColors.kt
Labels: fix

#325 Add depth to `BulletHandler`
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/BulletHandler.kt
Labels: feature

#326 Move primary text color specification to text styles
  multiplatform-markdown-renderer-code/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHighlightedCode.kt
  multiplatform-markdown-renderer-m2/api/android/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/jvm/multiplatform-markdown-renderer-m2.api
  multiplatform-markdown-renderer-m2/api/multiplatform-markdown-renderer-m2.klib.api
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/MarkdownColors.kt
  multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/MarkdownTypography.kt
  multiplatform-markdown-renderer-m3/api/android/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/jvm/multiplatform-markdown-renderer-m3.api
  multiplatform-markdown-renderer-m3/api/multiplatform-markdown-renderer-m3.klib.api
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/MarkdownColors.kt
  multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/MarkdownTypography.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownBlockQuote.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownColors.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownTypography.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt
Labels: feature

#327 Support image in tables
  README.md
  app-desktop/src/jvmMain/kotlin/main.kt
  multiplatform-markdown-renderer-code/api/android/multiplatform-markdown-renderer-code.api
  multiplatform-markdown-renderer-code/api/jvm/multiplatform-markdown-renderer-code.api
  multiplatform-markdown-renderer-code/api/multiplatform-markdown-renderer-code.klib.api
  multiplatform-markdown-renderer-code/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHighlightedCode.kt
  multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
  multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownBlockQuote.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
  multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
Labels: feature
